{
  "data":["java.lang.RuntimeException: An error occured while executing doInBackground()",
  "at android.os.AsyncTask$3.done (AsyncTask.java:300)",
  "at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:355)",
  "at java.util.concurrent.FutureTask.setException (FutureTask.java:222)",
  "at java.util.concurrent.FutureTask.run (FutureTask.java:242)",
  "at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:231)",
  "at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)",
  "at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)",
  "at java.lang.Thread.run Caused by: java.lang.NullPointerException (Thread.java:841)",
  "at com.teletalkvi.core.BaseAsyncTask.doInBackground (BaseAsyncTask.java:62)",
  "at com.teletalkvi.core.BaseAsyncTask.doInBackground (BaseAsyncTask.java:1)",
  "at android.os.AsyncTask$2.call (AsyncTask.java:288)",
  "at java.util.concurrent.FutureTask.run (FutureTask.java:237)",
  "... 4 more"]
}
